### ISSUE TITLE
Borked on mobile

### ISSUE THREAD

**Issue by henrik** [stevedomin/ex_playground#1]
Hey,

Love the site! Tried using it from my phone and sadly it didn't work. Looks like this:

![screenshot 2015-11-14 14 12 59](https://cloud.githubusercontent.com/assets/216/11163715/d427a6e4-8ad9-11e5-9080-d1ba29d9e43b.png)

That is the iPhone 6 emulation mode in Chrome.

**Comment by stevedomin** [comment]
Hi @henrik,

Thanks for the feedback!

It has been mentioned to me a couple of times now, I need to do something about it :)

I should be able to get some free time to look into that over the week-end, hopefully I can fix this.

**Comment by henrik** [comment]
Awesome! 💚

**Comment by stevedomin** [comment]
@henrik took me a while but I slightly improved the rendering on mobile. It's not amazing but it works. Would love to have your feedback on it.

**Comment by henrik** [comment]
@stevedomin Just tried it on my phone. Seems to work well. Good job!
