### ISSUE TITLE
Share -> Gist

### ISSUE THREAD

**Issue by sotojuan** [stevedomin/ex_playground#2]
Users should be available to generate an anonymous GitHub Gist of their code.

See https://play.rust-lang.org/

**Comment by stevedomin** [comment]
This should not be too hard to implement. Do you want to give it a go?

**Comment by sotojuan** [comment]
It'll take me some time to get to but I'll give it a shot!

**Comment by stevedomin** [comment]
@sotojuan no worries just let me know when you have something!
